"""Email delivery service using SendGrid."""
from typing import Optional
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, Email, To, Content
from app.config import settings


class EmailService:
    """Service for sending emails via SendGrid."""
    
    def __init__(self):
        self.api_key = settings.sendgrid_api_key
        self.from_email = settings.sendgrid_from_email
        self.client = SendGridAPIClient(self.api_key) if self.api_key else None
    
    def send_blog_post_email(
        self,
        to_email: str,
        blog_title: str,
        blog_content: str,
        video_title: str,
        channel_name: str
    ) -> bool:
        """
        Send blog post via email.
        
        Args:
            to_email: Recipient email address
            blog_title: Title of the blog post
            blog_content: Full blog content (markdown)
            video_title: Original YouTube video title
            channel_name: YouTube channel name
            
        Returns:
            True if email sent successfully, False otherwise
        """
        if not self.client:
            print("SendGrid client not configured - skipping email")
            return False
        
        try:
            # Create email content
            subject = f"Your Blog Post: {blog_title}"
            
            html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
        }}
        .header h1 {{
            margin: 0;
            font-size: 28px;
        }}
        .metadata {{
            background: #f7f7f7;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 30px;
        }}
        .metadata p {{
            margin: 5px 0;
            color: #666;
        }}
        .content {{
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .footer {{
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            color: #999;
            font-size: 14px;
        }}
        h2 {{
            color: #667eea;
            margin-top: 30px;
        }}
        code {{
            background: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
        }}
        pre {{
            background: #f4f4f4;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>✨ Your Blog Post is Ready!</h1>
    </div>
    
    <div class="metadata">
        <p><strong>📺 Source Video:</strong> {video_title}</p>
        <p><strong>📢 Channel:</strong> {channel_name}</p>
        <p><strong>📝 Generated:</strong> Just now</p>
    </div>
    
    <div class="content">
        {self._markdown_to_html(blog_content)}
    </div>
    
    <div class="footer">
        <p>Generated by YouTube to Blog AI Agent</p>
        <p>Powered by LangChain + LangGraph</p>
    </div>
</body>
</html>
            """
            
            message = Mail(
                from_email=Email(self.from_email),
                to_emails=To(to_email),
                subject=subject,
                html_content=Content("text/html", html_content)
            )
            
            # Send email
            response = self.client.send(message)
            
            if response.status_code in [200, 202]:
                print(f"Email sent successfully to {to_email}")
                return True
            else:
                print(f"Email send failed: {response.status_code}")
                return False
                
        except Exception as e:
            print(f"Email send error: {str(e)}")
            return False
    
    def _markdown_to_html(self, markdown_text: str) -> str:
        """
        Convert markdown to HTML (basic conversion).
        For production, use a library like python-markdown.
        """
        try:
            import markdown
            return markdown.markdown(
                markdown_text,
                extensions=['extra', 'codehilite', 'fenced_code']
            )
        except ImportError:
            # Fallback to basic conversion
            html = markdown_text.replace('\n\n', '</p><p>')
            html = html.replace('# ', '<h1>').replace('\n', '</h1>\n', 1)
            html = html.replace('## ', '<h2>').replace('\n', '</h2>\n', 1)
            html = html.replace('### ', '<h3>').replace('\n', '</h3>\n', 1)
            return f'<p>{html}</p>'
